<?php

/* Similar to Drupal 7, but we point to a route_name.
Also, many things are controlled through the routing, not here (e.g., permissions). */
/**
 * Implements hook_menu().
 */
function bartender_menu() {
  $items['bartender/home'] = array(
    'title' => 'Welcome to Bartender',
    'route_name' => 'bartender.home'
  );
  $items['admin/bartender/settings'] = array(
    'title' => 'Bartender Settings',
    'route_name' => 'bartender.settings'
  );
  return $items;
}

// Same as Drupal 7.
/**
 * Implements hook_permission().
 */
function bartender_permission() {
  return array(
    'use bartender' => array(
      'title' => t('Use bartender'),
    ),
    'administer bartender' => array(
      'title' => t('Administer bartender'),
    ),
  );
}