id: node.field_bartender_sweetness
uuid: 9c173af3-0890-457f-9000-e6e174e526b5
status: '1'
langcode: en
name: field_bartender_sweetness
entity_type: node
type: taxonomy_term_reference
settings:
  allowed_values:
    -
      vocabulary: liquors
      parent: '0'
  options_list_callback: ''
module: taxonomy
active: '1'
locked: '0'
cardinality: '1'
translatable: '0'
indexes: {  }
